version: "3.8"

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend-blue:
    build: ./frontend-blue
    ports:
      - "3000:3000"

  frontend-green:
    build: ./frontend-green
    ports:
      - "3001:3000"
